### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by gwiplot** [marsmarcin/Visual-of-Social-GAN#4]
Traceback (most recent call last):
  File "C:/Users/Desktop/sgan-master/plot_model03.py", line 223, in <module>
    main(args)
  File "C:/Users/Desktop/sgan-master/plot_model03.py", line 199, in main
    if os.path.isdir(args.model_path):
TypeError: _isdir: path should be string, bytes or os.PathLike, not NoneType
这是输出显示的错误

**Comment by marsmarcin** [comment]
截图

**Comment by gwiplot** [comment]
已经解决了，谢谢，之前是在pycharm里运行的。cmd里就好了。我问一下，sGAN源代码里运行train，之前可以运行，之后再运行显示FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'datasets\\zara1\\train'。并且第一次运行结果，有模型和没模型文件相差特别大，一个1527，一个48539kb,您知道为什么吗
